version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: backend/Dockerfile
    volumes:
      - ./backend:/var/www
    ports:
      - "8000:8000"
    environment:
      - APP_ENV=${APP_ENV}
      - DB_HOST=${DB_HOST} 
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    command: php artisan serve --host=0.0.0.0 --port=8000

  node:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/frontend
    ports:
      - "3000:3000"
