services:
  - type: web
    name: laravel-app
    env: docker
    plan: free
    region: singapore
    dockerfilePath: backend/Dockerfile
    rootDir: backend
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
      - key: APP_DEBUG
        value: false
      - key: LOG_CHANNEL
        value: stderr
